name: Build KFP Images (TEMPLATE)
on:
  workflow_call:
    inputs:
      image_name_prefix:
        required: true
        description: "the image name prefix for all images (e.g. ghcr.io/deployKF/kubeflow-pipelines)"
        type: string

      build_platforms:
        required: true
        description: "docker buildx platforms to build for, whitespace separated"
        type: string
      build_cache_prefix:
        required: true
        description: "the image name prefix for all registry build caches (e.g. ghcr.io/deployKF/ci/kubeflow-pipelines)"
        type: string

      tag_with_latest:
        default: false
        description: "if true, image tags will include 'latest'"
        type: boolean
      tag_with_semver:
        default: false
        description: "if true, image tags will include the version (from git tag event, without 'v' prefix)"
        type: boolean
      tag_with_sha:
        default: false
        description: "if true, image tags will include the commit SHA (both short and long)"
        type: boolean

      login_to_ghcr:
        default: false
        description: "if true, login to GitHub Container Registry with the GITHUB_TOKEN"
        type: boolean
      login_to_docker:
        default: false
        description: "if true, login to DockerHub using the DOCKER_USERNAME and DOCKER_PASSWORD secrets in the repository"
        type: boolean

jobs:
  ## ================================================================
  ## UPSTREAM IMAGE: gcr.io/ml-pipeline/kfp-launcher
  ## ================================================================
  ##
  ## NOTES:
  ##  - we ONLY build the kfp-launcher, we don't use the rest of the images
  ##  - we backport our object store fixes to 'v2-compatible' mode runs by using this image
  ##  - this Dockerfile is in a different location from KFP v2
  ##
  build__pipeline_launcher:
    name: Build - Pipeline Launcher
    uses: ./.github/workflows/build_image_TEMPLATE.yml
    secrets: inherit
    with:
      image_names: ${{ inputs.image_name_prefix }}/kfp-launcher

      metadata_title: "Kubeflow Pipelines - Pipeline Launcher"
      metadata_description: "The pipeline launcher for Kubeflow Pipelines, used in workflow runs."

      tag_with_latest: ${{ inputs.tag_with_latest }}
      tag_with_semver: ${{ inputs.tag_with_semver }}
      tag_with_sha: ${{ inputs.tag_with_sha }}

      build_file: ./v2/container/launcher/Dockerfile
      build_context: .
      build_platforms: ${{ inputs.build_platforms }}
      build_registry_cache: ${{ inputs.build_cache_prefix }}/kfp-launcher:build-cache

      login_to_ghcr: ${{ inputs.login_to_ghcr }}
      login_to_docker: ${{ inputs.login_to_docker }}
